name: somativafinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.0.0
  geolocator: ^14.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.18.1
  image_picker: ^1.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
